services:
    service_database:
        image: bitnami/postgresql:16.3.0
        environment:
            POSTGRESQL_USERNAME: service
            POSTGRESQL_PASSWORD: service
            POSTGRESQL_DATABASE: service
        ports:
            - 5432:5432

    keycloak:
        image: bitnami/keycloak:24.0.5
        environment:
            KEYCLOAK_IMPORT: src/main/resources/keycloak-realm-export.json
            KEYCLOAK_HTTP_PORT: 8000
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin

            KEYCLOAK_DATABASE_HOST: keycloak_database
            KEYCLOAK_DATABASE_PORT: 5000
            KEYCLOAK_DATABASE_USER: keycloak
            KEYCLOAK_DATABASE_NAME: keycloak
            KEYCLOAK_DATABASE_PASSWORD: keycloak
        depends_on:
            - keycloak_database
        ports:
            - 8000:8000

    keycloak_database:
        image: bitnami/postgresql:16.3.0
        environment:
            POSTGRESQL_USERNAME: keycloak
            POSTGRESQL_PASSWORD: keycloak
            POSTGRESQL_DATABASE: keycloak
            POSTGRESQL_PORT_NUMBER: 5000
