quarkus:
  smallrye-openapi:
    path: /openapi
    store-schema-directory: target
  swagger-ui:
    always-include: true
    path: /swagger-ui

"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      reactive:
        url: vertx-reactive:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}
    hibernate-orm:
      database:
        generation:
          ~: update
          create-schemas: true

    oidc:
      auth-server-url: ${OIDC_AUTH_SERVER_URL}
      client-id: ${OIDC_CLIENT_ID}
      token:
        issuer: ${OIDC_TOKEN_JWT_ISSUER}
        audience: ${OIDC_TOKEN_JWT_AUDIENCE}

  api-keys: ${API_KEYS}

"%test":
  quarkus:
    datasource:
      db-kind: postgresql
      devservices:
        enabled: true
        port: 5432
        username: service
        password: service
    hibernate-orm:
      database:
        generation: drop-and-create

  api-keys: test

"%dev":
  quarkus:
    log:
      level:
        category:
          "insta_toggles":
              level: DEBUG

    datasource:
      db-kind: postgresql
      devservices:
        enabled: true
        port: 5432
        username: service
        password: service
    hibernate-orm:
      database:
        generation: drop-and-create

    keycloak:
      devservices:
        enabled: true
        port: 8000
        realm-name: insta-toggles
        realm-path: example-keycloak-settings.json

  api-keys: test
