quarkus:
  datasource:
    db-kind: postgresql

  smallrye-openapi:
    path: /openapi
    store-schema-directory: target

  swagger-ui:
    always-include: true
    path: /swagger-ui

  jacoco:
    excludes: "CustomAuthorizationController.class"

api:
  key:
    enable: ${SERVICE_API_KEY_ENABLE:true}
    values: ${SERVICE_API_KEY_VALUES: }
  authorization:
    enable: ${SERVICE_API_AUTHORIZATION_ENABLE:true}

use-testing-context: ${SERVICE_USE_TESTING_CONTEXT:false}

"%prod":
  quarkus:
    datasource:
      username: ${SERVICE_DATASOURCE_USERNAME}
      password: ${SERVICE_DATASOURCE_PASSWORD}
      reactive:
        url: vertx-reactive:postgresql://${SERVICE_DATASOURCE_HOST}:${SERVICE_DATASOURCE_PORT}/${SERVICE_DATASOURCE_DATABASE}
    hibernate-orm:
      database:
        generation:
          ~: update
          create-schemas: true

    oidc:
      auth-server-url: ${SERVICE_OIDC_AUTH_SERVER_URL}
      client-id: ${SERVICE_OIDC_CLIENT_ID}
      token:
        issuer: ${SERVICE_OIDC_TOKEN_JWT_ISSUER}
        audience: ${SERVICE_OIDC_TOKEN_JWT_AUDIENCE}

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        port: 5432
        username: service
        password: service
    hibernate-orm:
      database:
        generation: drop-and-create

  smallrye-openapi:
    enable: false

  swagger-ui:
    enable: false

  api:
    key:
      values: test

"%dev":
  quarkus:
    log:
      level:
        category:
          "insta_toggles":
            level: DEBUG

    datasource:
      devservices:
        enabled: true
        port: 5432
        username: service
        password: service
    hibernate-orm:
      database:
        generation: drop-and-create

    keycloak:
      devservices:
        enabled: true
        port: 8000
        realm-name: insta-toggles
        realm-path: example-keycloak-settings.json

  api:
    key:
      values: test
