name: Service - Check Image Security

on:
  push:
    branches:
      - 'main'
    paths:
      - 'service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from pom.xml file
        id: project
        uses: dostonhamrakulov/maven-artifact-version-extractor@v1.0
        with:
          file_path: ${{ github.workspace }}/service/pom.xml

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/sebastian-struecker/simple-feature-toggles/service:${{ steps.project.outputs.version }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
